apiVersion: v1
kind: ImageStream
metadata:
  generation: 1
  labels:
    app: digital-service-banker-assignment-test-apiserver
  name: digital-service-banker-assignment-test-apiserver
  namespace: dct-nextgen-services
spec:
  dockerImageRepository: artrepo.firstrepublic.com:5101/digital-service-banker-assignment-test-apiserver

